version: '3.8'
services:
  backend:
    build: ./backend
    container_name: ecfr_backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecfr_data
      - ELASTIC_NODE=http://elasticsearch:9200
      - GEMINI_API_KEY=your_api_key_here # Replace with your actual key
    depends_on:
      - mongo
      - elasticsearch
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ecfr_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: ecfr_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: ecfr_elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Recommended for development
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  mongo-data:
  es-data:
